const options = [
    "Acorn",
    "Aerocuda Wing",
    "Ancient Arowana",
    "Apple",
    "Big Hearty Radish",
    "Big Hearty Truffle",
    "Bird Egg",
    "Bladed Rhino Beetle",
    "Blue Bokoblin Horn",
    "Blue Boss Bokoblin Horn",
    "Blue Hinox Horn",
    "Blue Horriblin Horn",
    "Blue Lizalfos Horn",
    "Bright-Eyed Crab",
    "Brightcap",
    "Bokoblin Fang",
    "Bokoblin Guts",
    "Bomb Flower",
    "Boss Bokoblin Guts",
    "Boss Bokoblin Horn",
    "Cane Sugar",
    "Chillfin Trout",
    "Chillshroom",
    "Chuchu Jelly",
    "Cold Darner",
    "Cool Safflina",
    "Courser Bee Honey",
    "Dark Clump",
    "Dazzle Fruit",
    "Deep Firefly",
    "Electric Darner",
    "Electric Keese Eyeball",
    "Electric Lizalfos Horn",
    "Electric Safflina",
    "Endura Carrot",
    "Endura Shroom",
    "Energetic Rhino Beetle",
    "Fire Fruit",
    "Fire Keese Eyeball",
    "Fire-Breath Lizalfos Horn",
    "Fire-Like Stone",
    "Fireproof Lizard",
    "Fleet-Lotus",
    "Fortified Pumpkin",
    "Fresh Milk",
    "Frox Fang",
    "Frox Fingernail",
    "Frox Guts",
    "Gibdo Guts",
    "Gibdo Wing",
    "Gleeok Flame Horn",
    "Gleeok Frost Horn",
    "Gleeok Guts",
    "Gleeok Thunder Horn",
    "Gorod Spice",
    "Goron Spice",
    "Glowing Cave Fish",
    "Goat Butter",
    "Golden Apple",
    "Hearty Lizard",
    "Hearty Radish",
    "Hearty Salmon",
    "Hightail Lizard",
    "Hinox Horn",
    "Hinox Tooth",
    "Horned Beetle",
    "Horriblin Claw",
    "Horriblin Guts",
    "Hot-Footed Frog",
    "Hylian Rice",
    "Hylian Shroom",
    "Hylian Tomato",
    "Hydromelon",
    "Hyrule Bass",
    "Hyrule Herb",
    "Ice Fruit",
    "Ice Keese Eyeball",
    "Ice-Like Stone",
    "Ironshroom",
    "Keese Eyeball",
    "Korok Frond",
    "Lizalfos Horn",
    "Lizalfos Tail",
    "Like-Like Stone",
    "Lynel Guts",
    "Lynel Hoof",
    "Lynel Mace Horn",
    "Lynel Saber Horn",
    "Mighty Bananas",
    "Mighty Carp",
    "Mighty Porgy",
    "Mighty Salmon",
    "Moblin Fang",
    "Moblin Guts",
    "Monster Extract",
    "Molduga Fin",
    "Molduga Guts",
    "Molduga Jaw",
    "Octo Balloon",
    "Octorok Tentacle",
    "Oil Jar",
    "Palm Fish",
    "Palm Fruit",
    "Puffshroom",
    "Razorclaw Crab",
    "Razorshroom",
    "Red Chuchu Jelly",
    "Restless Cricket",
    "Rock Salt",
    "Rugged Rhino Beetle",
    "Rushroom",
    "Sanke Carp",
    "Shock Fruit",
    "Shock-Like Stone",
    "Silent Princess",
    "Silent Shroom",
    "Silver Bokoblin Horn",
    "Silver Boss Bokoblin Horn",
    "Silver Hinox Horn",
    "Silver Horriblin Horn",
    "Silver Lizalfos Horn",
    "Silver Lynel Saber Horn",
    "Silver Moblin Horn",
    "Silver-Lynel Mace Horn",
    "Sizzlefin Trout",
    "Smotherwing Butterfly",
    "Splash Fruit",
    "Stalnox Horn",
    "Stambulb",
    "Stamella Shroom",
    "Staminoka Bass",
    "Star Fragment",
    "Stealthfin Trout",
    "Sticky Frog",
    "Sticky Lizard",
    "Stinkshroom",
    "Summerwing Butterfly",
    "Sun Pumpkin",
    "Sunshroom",
    "Sundelion",
    "Swift Carrot",
    "Swift Violet",
    "Tabantha Wheat",
    "Thunderwing Butterfly",
    "Tireless Frog",
    "Voltfin Trout",
    "Voild Fruit",
    "Warm Darner",
    "White Bokoblin Horn",
    "White Boss Bokoblin Horn",
    "White Lizalfos Horn",
    "White-Maned Lynel Mace Horn",
    "Wildberry",
    "Winterwing Butterfly",
    "Yellow Chuchu Jelly",
    "Zapshroom",
  ];

  export default options;